### ISSUE TITLE
Enable/Disable Register Page Filter

### ISSUE THREAD

**Issue by turtlepod** [Astoundify/woocommerce-simple-registration#18]
WooCommerce Select Page Field do not have "option none" so, it's impossible to disable filter to register page.

**Comment by spencerfinnell** [comment]
Not sure it's a huge issue. If it's not available on the "My account page" field not sure we need it. Maybe a filter that can be turned off.

**Comment by turtlepod** [comment]
Apparently we can set the args in the field option
