### ISSUE TITLE
Update to WC 2.6.4

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/woocommerce-simple-registration#3]
Check template files, hooks, etc.

**Comment by adampickering** [comment]
Please read over the support topics posted here https://wordpress.org/support/plugin/woocommerce-simple-registration to see if we can improve this plugin for users, I believe we just need to update the plugin files to the latest WC version

**Comment by turtlepod** [comment]
I updated the plugin with new WC form + password meter now working.
https://github.com/Astoundify/woocommerce-simple-registration/tree/david
please check first, and pull/merge :)

**Comment by adampickering** [comment]
great i'll check this out today and if all is good, i'll merge and upload to wp.org
