### ISSUE TITLE
Allow WooCommerce Simple Registration to be output on the register shortcode.

### ISSUE THREAD

**Issue by adampickering** [Astoundify/woocommerce-simple-registration#4]
![screen shot 2016-09-16 at 1 02 56 pm](https://cloud.githubusercontent.com/assets/746776/18594383/b9edd976-7c0d-11e6-8ba7-f4717dec43b1.jpg)

![screen shot 2016-09-16 at 1 02 56 pm](https://cloud.githubusercontent.com/assets/746776/17253433/c7d43478-557e-11e6-90d6-d10c37c11951.jpg)

**Comment by spencerfinnell** [comment]
It's a limitation of the actual Social Login plugin, not this. You can only choose from 3 pages:

```
array(
				'name'     => __( 'Display Social Login buttons on:', 'woocommerce-social-login' ),
				'desc_tip' => __( 'Control where Social Login buttons are displayed.', 'woocommerce-social-login' ),
				'id'       => 'wc_social_login_display',
				'type'     => 'multiselect',
				'class'    => 'wc-enhanced-select',
				'options' => array(
					'checkout'        => __( 'Checkout', 'woocommerce-social-login' ),
					'my_account'      => __( 'My Account', 'woocommerce-social-login' ),
					'checkout_notice' => __( 'Checkout Notice', 'woocommerce-social-login' ),
				),
				'default'  => array(
					'checkout',
					'my_account',
				),
```

**Comment by adampickering** [comment]
If we hook into the widget, `woocommerce_social_login_buttions()` it would output them @spencerfinnell

**Comment by adampickering** [comment]
https://www.sellwithwp.com/create-sidebar-login-membership-site/#comment-342162 @spencerfinnell

**Comment by spencerfinnell** [comment]
There are very specific checks before outputting it:

```php
/**
	 * Render social login buttons on frontend
	 *
	 * @since 1.0
	 */
	public function render_social_login_buttons() {
		if ( ! is_checkout() && ! is_account_page() ) {
			return;
		}
		if ( is_checkout() && ! $this->is_displayed_on( 'checkout' ) ) {
			return;
		}
		if ( is_account_page() && ! $this->is_displayed_on( 'my_account' ) ) {
			return;
		}
		$return_url = is_checkout() ? WC()->cart->get_checkout_url() : wc_get_page_permalink( 'myaccount' );
		woocommerce_social_login_buttons( $return_url );
	}
```

It could be called directly but there has to be a reason they set it up like this.

**Comment by adampickering** [comment]
https://gist.github.com/bekarice/4d4b30384cb3c9b1886a#file-wc-social-login-comment-form-buttons-php

**Comment by spencerfinnell** [comment]
There is a built in shortcode though: 

`[woocommerce_social_login_buttons return_url="https://mystore.com/my-account"]`

So maybe it doesn't matter. This plugin would need to introduce a new option to show/hide it though.

**Comment by adampickering** [comment]
So just add it to the page? then we need to style it a bit?

![screen shot 2016-09-16 at 1 24 32 pm](https://cloud.githubusercontent.com/assets/746776/18595000/b5ff9d9c-7c10-11e6-8713-6cf5e1fe56b4.jpg)

**Comment by spencerfinnell** [comment]
Yes but could also be integrated in the plugin to output automatically as well.

**Comment by turtlepod** [comment]
I don't understand this task. This plugin output is using the register shortcode `[woocommerce_simple_registration]`.

> Allow WooCommerce Simple Registration to be output on the register shortcode.

Do you want to integrate social login? Is it using this plugin?
https://woocommerce.com/products/woocommerce-social-login/

Do you have the latest version available?

**Comment by adampickering** [comment]
> Do you want to integrate social login? Is it using this plugin?

Yes.

> Do you have the latest version available?

Yes, I sent you a copy.

@turtlepod
