### ISSUE TITLE
Add more fields, name, first and last like screenshot.

### ISSUE THREAD

**Issue by adampickering** [Astoundify/woocommerce-simple-registration#5]
![sign up advanced](https://cloud.githubusercontent.com/assets/746776/17253440/cfcfa784-557e-11e6-8d07-373752c56910.jpg)

**Comment by turtlepod** [comment]
Do you want "first name" & "last name" only for this plugin output or do you want to also add this in WC default register form (e.g. in my account page)?

**Comment by spencerfinnell** [comment]
I think it should apply to both.

**Comment by turtlepod** [comment]
OK! I'll work on this today.

Note: I think it should be in another plugin because IMO this is out of scope of "simple registration" plugin.

**Comment by spencerfinnell** [comment]
I agree as well... Either the plugin should be renamed or it should be separate. 

@adampickering thoughts?

**Comment by Garconis** [comment]
@adampickering is that a mock-up or an actual functioning registration form for Listify? 

Any update on this? At least the option of adding a name would be ideal.
